"""The docs must name only what the code has, and must not leak. No docs build needed."""

import importlib
import importlib.util
import re
import types
from pathlib import Path

import pytest

from gatle_ignite.config.base import known_fields

ROOT = Path(__file__).resolve().parents[1]

# Marker that docs/gen_reference.py stamps into every page it writes.
_GENERATED = "Generated by docs/gen_reference.py"


def _is_generated(path):
    """Generated pages exist only after `mkdocs build`, so they would change the test count."""
    try:
        return _GENERATED in path.read_text()
    except OSError:
        return False


DOC_FILES = sorted(
    p for p in [*(ROOT / "docs").rglob("*.md"), ROOT / "README.md"] if not _is_generated(p)
)

# Pages is world-readable. A bracketed character keeps a pattern from matching its own line.
FORBIDDEN = (
    r"ghp_[A-Za-z0-9]{20,}",  # GitHub PAT
    r"github[_]pat_[A-Za-z0-9_]{20,}",
    r"sk-[A-Za-z0-9]{20,}",  # OpenAI-style key
    r"xox[baprs]-[A-Za-z0-9-]{10,}",  # Slack token
    r"AKIA[0-9A-Z]{16}",  # AWS access key id
    r"-----BEGIN [A-Z ]*PRIVATE KEY",
    r"discord\.com/api/webhooks/[0-9]",  # a real webhook, not the env var name
    r"\b[0-9a-f]{40}\b",  # a bare 40-hex secret (W&B keys are this shape)
    r"/[w]orkspace/",  # internal absolute paths
    r"/home/[a-z0-9_-]+/",
)

# ConfigDict's own API, plus "py": `--config=cfg.py` is a filename, not a field access.
_IGNORED_ATTRS = {"get", "keys", "items", "values", "lock", "unlock", "to_json_best_effort", "py"}

# Not after a slash: a URL or a file path is not a module path.
_DOTTED_RE = re.compile(r"(?<![/\w])gatle_ignite(?:\.[a-z_][a-z0-9_]*)+(?:\.\{[a-z_,\s]+\})?")

# A brace shorthand that enumerates builtins compactly:
# `gatle_ignite.optimizers.{adam,adamw,sgd}` -> three real paths.
_BRACE_RE = re.compile(r"^(.*)\.\{([a-z_,\s]+)\}$")


def _expand(dotted):
    match = _BRACE_RE.match(dotted)
    if not match:
        return [dotted]
    stem, leaves = match.groups()
    return [f"{stem}.{leaf.strip()}" for leaf in leaves.split(",") if leaf.strip()]


def _doc_id(path):
    return str(path.relative_to(ROOT))


def _scan_text(text, patterns):
    hits = []
    for pattern in patterns:
        for match in re.finditer(pattern, text, re.IGNORECASE):
            line = text[: match.start()].count("\n") + 1
            hits.append(f"{pattern!r} at line {line}: {match.group(0)[:40]!r}")
    return hits


def _scan(path, patterns):
    return _scan_text(path.read_text(), patterns)


# Authored prose only: a fenced block or a --8<-- include is copied, not read.
MAX_PROSE_LINES = 60

# status.md is a ledger: capping it would mean deleting verified claims.
CAP_EXEMPT = ("status.md",)


def _prose_lines(text):
    """Authored prose lines: fenced blocks, their contents and snippet includes excluded."""
    count, inside = 0, False
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("```"):
            inside = not inside
            continue
        if inside or not stripped or stripped.startswith("--8<--"):
            continue
        count += 1
    return count


CAPPED_FILES = [
    p
    for p in DOC_FILES
    if str(p).endswith(".md")
    and not any(part in CAP_EXEMPT for part in p.relative_to(ROOT).parts)
    and p.is_relative_to(ROOT / "docs")
]


@pytest.mark.parametrize("path", CAPPED_FILES, ids=_doc_id)
def test_no_page_runs_past_sixty_prose_lines(path):
    prose = _prose_lines(path.read_text())
    assert prose <= MAX_PROSE_LINES, (
        f"{_doc_id(path)} carries {prose} prose lines, cap is {MAX_PROSE_LINES}. Commands, "
        "output and --8<-- includes are free -- this is narrative. Cut it, or move what it "
        "explains to debugging.md (a trap) or status.md (a claim about what is verified)."
    )


@pytest.mark.parametrize("path", DOC_FILES, ids=_doc_id)
def test_no_credentials(path):
    hits = _scan(path, FORBIDDEN)
    assert not hits, f"{_doc_id(path)} contains forbidden content:\n  " + "\n  ".join(hits)


EM_DASH = "\u2014"

# The two generators print prose into pages.
EM_DASH_FILES = DOC_FILES + [
    ROOT / "docs" / "gen_reference.py",
    ROOT / "docs" / "hooks.py",
]


def _em_dash_lines(text):
    return [n for n, line in enumerate(text.splitlines(), 1) if EM_DASH in line]


@pytest.mark.parametrize("path", EM_DASH_FILES, ids=_doc_id)
def test_no_em_dash_in_the_docs(path):
    lines = _em_dash_lines(path.read_text())
    assert not lines, (
        f"{_doc_id(path)} has em dashes on lines {lines}. "
        "Use a comma, a colon, parentheses or a full stop instead."
    )


def test_no_em_dash_in_the_generated_pages():
    bad = {}
    for page, text in sorted(_render_generated_pages().items()):
        lines = _em_dash_lines(text)
        if lines:
            bad[page] = lines
    assert not bad, f"generated pages carry em dashes, by line: {bad}"


@pytest.mark.parametrize("path", DOC_FILES, ids=_doc_id)
def test_every_dotted_path_resolves(path):
    found = set()
    for match in _DOTTED_RE.findall(path.read_text()):
        found.update(_expand(match))

    bad = []
    for dotted in sorted(found):
        if dotted.endswith(".git"):
            continue
        try:
            importlib.import_module(dotted)
        except ImportError:
            module, _, attr = dotted.rpartition(".")  # maybe it names an attribute
            try:
                getattr(importlib.import_module(module), attr)
            except (ImportError, AttributeError):
                bad.append(dotted)
    assert not bad, f"{_doc_id(path)} names unimportable paths: {bad}"


# A path to an example file, as prose or as a snippet include: `examples/gan/scripts/verify.py`.
_EXAMPLE_PATH_RE = re.compile(r"\bexamples/[\w./-]*\.py\b")

# Only `python -m`: debugging.md quotes a deliberate typo, 'examples.synthetic.models.mpl'.
_RUN_MODULE_RE = re.compile(r"python -m (examples\.[a-z_][a-z0-9_.]*)")


def _missing_example_paths(text):
    return sorted({m for m in _EXAMPLE_PATH_RE.findall(text) if not (ROOT / m).exists()})


@pytest.mark.parametrize("path", DOC_FILES, ids=_doc_id)
def test_every_example_path_a_doc_names_exists(path):
    """mkdocs checks `--8<--` includes but not prose, which is where the instructions live."""
    missing = _missing_example_paths(path.read_text())
    assert not missing, f"{_doc_id(path)} names example files that do not exist: {missing}"


@pytest.mark.parametrize("path", DOC_FILES, ids=_doc_id)
def test_every_runnable_module_a_doc_names_imports(path):
    bad = []
    for dotted in set(_RUN_MODULE_RE.findall(path.read_text())):
        if importlib.util.find_spec(dotted) is None:
            bad.append(dotted)
    assert not bad, f"{_doc_id(path)} says to run modules that do not exist: {bad}"


def test_the_generated_pages_name_real_example_files():
    """Generated pages quote error strings that cite examples, and DOC_FILES misses them."""
    bad = {}
    for page, text in _render_generated_pages().items():
        missing = _missing_example_paths(text)
        if missing:
            bad[page] = missing
    assert not bad, f"generated pages name example files that do not exist: {bad}"


def test_the_generated_pages_carry_no_credentials_or_internal_paths():
    """Generated pages copy literal values out of source; DOC_FILES misses them."""
    bad = {}
    for page, text in sorted(_render_generated_pages().items()):
        hits = _scan_text(text, FORBIDDEN)
        if hits:
            bad[page] = hits
    assert not bad, f"generated pages contain forbidden content: {bad}"


# Names docs/steps/ invents to show extending the framework: their fields are not in base_config().
_DOC_EXAMPLE_ENGINE = "raw"  # the engine examples/ema/ declares via eval_specs()
_DOC_EXAMPLE_LOADER = "dictionary"  # the extra dataloader built via get_dataset()


@pytest.mark.parametrize("path", DOC_FILES, ids=_doc_id)
def test_every_config_field_is_known(path):
    from gatle_ignite import EngineSpec

    engine = EngineSpec.for_split(_DOC_EXAMPLE_ENGINE)
    engine_fields = {
        engine.metrics_field,
        engine.every_field,
        engine.length_field,
        engine.score_field,
        engine.score_factor_field,
        engine.early_stop_patience_field,
        engine.early_stop_after_field,
        f"{engine.split}_ds_name",
        f"{engine.split}_ds_params",
    }
    known = (
        set(known_fields())
        | engine_fields
        | {f"{_DOC_EXAMPLE_LOADER}_ds_name", f"{_DOC_EXAMPLE_LOADER}_ds_params"}
    )
    used = set(re.findall(r"\bcfg\.([a-z_][a-z0-9_]*)\b", path.read_text()))
    unknown = sorted(used - known - _IGNORED_ATTRS)
    assert not unknown, f"{_doc_id(path)} names unknown config fields: {unknown}"


# BaseTrainer methods a task drives but never overrides. Anything else must be in the guide.
_NOT_EXTENSION_POINTS = {
    "attach_metrics",
    "attach_progress",
    "build_criterion",
    "build_optimizer",
    "build_scheduler",
    "init_metrics",
    "loss_fn",
    "teardown",
}


def test_the_guide_names_every_extension_point():
    """The reverse check: a new public BaseTrainer method is documented or declared plumbing."""
    import inspect

    from gatle_ignite.trainer.base import BaseTrainer

    documented = (ROOT / "docs" / "reference" / "api.md").read_text() + "".join(
        p.read_text() for p in sorted((ROOT / "docs" / "steps").glob("*.md"))
    )
    public = {
        name
        for name, _ in inspect.getmembers(BaseTrainer, inspect.isfunction)
        if not name.startswith("_")
    }
    undocumented = sorted(name for name in public - _NOT_EXTENSION_POINTS if name not in documented)
    assert not undocumented, (
        "neither docs/reference/api.md nor docs/steps/ mentions these BaseTrainer methods: "
        f"{undocumented}. Document them, or add them to _NOT_EXTENSION_POINTS if a task "
        "is never meant to override them."
    )


def test_the_plumbing_list_has_not_rotted():
    """A stale exemption would silently excuse a new method that later took its name."""
    import inspect

    from gatle_ignite.trainer.base import BaseTrainer

    public = {
        name
        for name, _ in inspect.getmembers(BaseTrainer, inspect.isfunction)
        if not name.startswith("_")
    }
    stale = sorted(_NOT_EXTENSION_POINTS - public)
    assert not stale, f"_NOT_EXTENSION_POINTS names methods that no longer exist: {stale}"


def test_generated_config_reference_covers_every_field():
    import ast
    import inspect

    from gatle_ignite.config import base
    from gatle_ignite.config.base import OPTIONAL_KNOWN

    tree = ast.parse(inspect.getsource(base))
    fn = next(n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name == "base_config")
    from_ast = {
        s.targets[0].attr
        for s in fn.body
        if isinstance(s, ast.Assign) and isinstance(s.targets[0], ast.Attribute)
    }

    # The generator reads base_config() by AST, to see the comments; pin that to what it builds.
    assert from_ast == set(base.base_config().keys())
    assert set(known_fields()) == from_ast | set(OPTIONAL_KNOWN)


def _exec_generator():
    """`(module, {path: markdown})`: the generator run with mkdocs_gen_files stubbed."""
    import importlib.util
    import io
    import sys

    written = {}

    class _Capture(io.StringIO):
        def __init__(self, path):
            super().__init__()
            self._path = path

        def __enter__(self):
            return self

        def __exit__(self, *exc):
            written[self._path] = self.getvalue()
            return False

    stub = types.ModuleType("mkdocs_gen_files")
    stub.open = lambda path, mode="r": _Capture(path)
    stub.set_edit_path = lambda *a, **k: None

    real = sys.modules.get("mkdocs_gen_files")
    sys.modules["mkdocs_gen_files"] = stub
    try:
        spec = importlib.util.spec_from_file_location(
            "_gen_reference_under_test", ROOT / "docs" / "gen_reference.py"
        )
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
    finally:
        if real is None:
            del sys.modules["mkdocs_gen_files"]
        else:
            sys.modules["mkdocs_gen_files"] = real
    return module, written


def _render_generated_pages():
    """What docs/gen_reference.py would write, so tests read the page rather than its inputs."""
    return _exec_generator()[1]


def test_the_rendered_config_page_names_every_field():
    from gatle_ignite.config.base import base_config

    page = _render_generated_pages()["reference/config.md"]
    missing = sorted(f for f in base_config() if not re.search(rf"\b{re.escape(f)}\b", page))
    assert not missing, f"the generated config reference renders no row for: {missing}"


def test_every_field_commented_in_the_source_renders_its_note():
    """The oracle is the source, read independently of the generator.

    A generator that loses a note reports the field as uncommented, so looping over its output
    would skip the very field that broke. `ruff format` moving a trailing note is one cause.
    """
    import ast
    import inspect
    import io
    import tokenize

    from gatle_ignite.config import base

    source = inspect.getsource(base)
    commented_lines = {
        tok.start[0]
        for tok in tokenize.generate_tokens(io.StringIO(source).readline)
        if tok.type == tokenize.COMMENT and tok.line[: tok.start[1]].strip()
    }
    fn = next(
        n
        for n in ast.parse(source).body
        if isinstance(n, ast.FunctionDef) and n.name == "base_config"
    )
    commented_fields = {
        stmt.targets[0].attr
        for stmt in fn.body
        if isinstance(stmt, ast.Assign)
        and isinstance(stmt.targets[0], ast.Attribute)
        and any(stmt.lineno <= line <= stmt.end_lineno for line in commented_lines)
    }

    # `| `name` **(required)** | `str` | _unset_ | the note |` -> ("name", "the note").
    # Split on unescaped pipes only: amp_dtype's note is itself a row of escaped ones.
    row_re = re.compile(r"^\|\s*`(\w+)`(?:\s*\*\*\(required\)\*\*)?\s*\|(.*)\|\s*$")
    notes = {}
    for line in _render_generated_pages()["reference/config.md"].splitlines():
        match = row_re.match(line)
        if match:
            notes[match.group(1)] = re.split(r"(?<!\\)\|", match.group(2))[-1].strip()

    assert len(commented_fields) > 20, (
        f"only {len(commented_fields)} commented fields found in the source -- this test's "
        "own parsing of config/base.py has broken, not the generator"
    )
    blank = sorted(f for f in commented_fields if not notes.get(f))
    assert not blank, (
        f"these fields carry a comment in config/base.py but render an empty Notes cell: "
        f"{blank}. The generator lost the comment between the source and the page."
    )


def test_the_rendered_contracts_page_states_the_real_contracts():
    """Every contract in dispatch.CONTRACTS must reach the page a user actually reads."""
    from gatle_ignite.dispatch import CONTRACTS

    page = _render_generated_pages()["reference/contracts.md"]
    missing = [attr for _field, attr, _contract, _fields in CONTRACTS if attr not in page]
    assert not missing, f"the generated contracts page omits: {missing}"


# A signature a doc writes out longhand: `get_scheduler(cfg, train_dl, optimizer, engines)`.
_SIGNATURE_RE = re.compile(r"\b(get_[a-z_]+)\(([^)]*)\)")


def _normative_lines(text):
    """Code blocks and table rows: prose may quote a wrong signature so you recognise it."""
    fenced = False
    for line in text.splitlines():
        if line.lstrip().startswith("```"):
            fenced = not fenced
            continue
        if fenced or line.startswith("|"):
            yield line


# Entrypoints a builtin implements. Trainer, Model, Loss and Transformation take task params.
_REFERENCE_IMPL = {
    "get_scheduler": "gatle_ignite.schedulers.cosine",
    "get_optimizer": "gatle_ignite.optimizers.adamw",
    "get_metric": "examples.synthetic.metrics.accuracy",
}


@pytest.mark.parametrize("path", DOC_FILES, ids=_doc_id)
def test_no_doc_advertises_an_entrypoint_signature_the_code_would_reject(path):
    """Only leading positional names, up to the first `**kwargs` or default, are compared.

    `get_optimizer(model, **params)` names what the framework passes, not all adamw takes. A
    non-identifier argument means a call, not a signature, so there is nothing to check.
    """
    import inspect

    bad = []
    for entrypoint, written in _SIGNATURE_RE.findall("\n".join(_normative_lines(path.read_text()))):
        module = _REFERENCE_IMPL.get(entrypoint)
        if module is None:
            continue
        documented = []
        for param in (p.strip() for p in written.split(",")):
            if param.startswith("*") or "=" in param:
                break  # the doc stops naming positionals here; so do we
            documented.append(param)
        if not documented or not all(p.isidentifier() for p in documented):
            continue
        real = list(
            inspect.signature(getattr(importlib.import_module(module), entrypoint)).parameters
        )
        if documented != real[: len(documented)]:
            bad.append(
                f"{entrypoint}({', '.join(documented)}) -- real: {entrypoint}({', '.join(real)})"
            )
    assert not bad, f"{_doc_id(path)} advertises signatures the code does not have: {bad}"


# A "where things go" table's last column. `gatle_ignite.optimizers.*` names a namespace.
_BUILTIN_IN_TABLE_RE = re.compile(r"gatle_ignite(?:\.[a-z_][a-z0-9_]*)+(\.\*)?")

_LAYOUT_TABLES = [ROOT / "src" / "gatle_ignite" / "_template" / "README.md-tpl"]


def _table_rows(text):
    for line in text.splitlines():
        if line.startswith("|") and line.count("|") == 5 and "---" not in line:
            yield [cell.strip().strip("`") for cell in line.strip().strip("|").split("|")]


@pytest.mark.parametrize("path", _LAYOUT_TABLES, ids=_doc_id)
def test_every_builtin_a_layout_table_offers_is_actually_selectable(path):
    """Importing is not enough: `gatle_ignite.data.helpers` imports but has no `get_sampler`."""
    from gatle_ignite.dispatch import CONTRACTS

    entrypoints = {attr for _field, attr, _contract, _fields in CONTRACTS}
    bad = []
    for row in _table_rows(path.read_text()):
        want, builtin = row[0], row[-1]
        for match in _BUILTIN_IN_TABLE_RE.finditer(builtin):
            dotted, is_namespace = match.group(0), match.group(1)
            if is_namespace:
                dotted = dotted[: -len(is_namespace)]
            module = importlib.import_module(dotted)
            if is_namespace:
                # A namespace is honest if any module under it is selectable.
                leaves = [
                    importlib.import_module(f"{dotted}.{p.stem}")
                    for p in Path(module.__file__).parent.glob("[a-z]*.py")
                    if not p.stem.startswith("_")
                ]
                if any(entrypoints & set(vars(leaf)) for leaf in leaves):
                    continue
            elif entrypoints & set(vars(module)):
                continue
            bad.append(f"{want!r} offers {match.group(0)}, which exposes no entrypoint")
    assert not bad, f"{_doc_id(path)} offers builtins a config cannot select: {bad}"


# --- the example pages' spines ------------------------------------------------------
#
# docs/hooks.py replaces each <!-- spine: example/config --> marker at build time.

EXAMPLE_PAGES = sorted((ROOT / "docs" / "examples").glob("*.md"))

# synthetic is the baseline every spine is measured against, so it has none of its own.
SPINE_EXEMPT = ("synthetic.md",)

_SPINE_MARKER = re.compile(r"^<!--\s*spine:\s*([\w.-]+)/([\w.-]+)\s*-->$", re.M)


def _hooks():
    spec = importlib.util.spec_from_file_location("gi_docs_hooks", ROOT / "docs" / "hooks.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _markers(path):
    return _SPINE_MARKER.findall(path.read_text())


@pytest.mark.parametrize("path", EXAMPLE_PAGES, ids=_doc_id)
def test_every_example_page_carries_a_resolvable_spine(path):
    """The spine is the only thing tying an example page back to the walk."""
    markers = _markers(path)
    if path.name in SPINE_EXEMPT:
        assert not markers, f"{_doc_id(path)} is the baseline; it must not carry a spine."
        return
    assert markers, (
        f"{_doc_id(path)} has no <!-- spine: example/config --> marker. Add one naming "
        "the config it documents."
    )
    # The hook's regex is anchored: a misplaced marker substitutes nothing, and the build passes.
    written = path.read_text().count("spine:")
    assert written == len(markers), (
        f"{_doc_id(path)} writes 'spine:' {written} times but only {len(markers)} are "
        "well-formed markers. A marker must start at column 0 with no trailing space."
    )
    hooks = _hooks()
    for example, stem in markers:
        block = hooks.spine(f"examples.{example}.configs.{stem}")
        assert block.strip(), f"{_doc_id(path)}: spine {example}/{stem} rendered empty."


def test_every_field_a_spine_names_is_documented_on_the_step_it_links_to():
    """A spine row must link to a step page that names its field."""
    hooks = _hooks()
    missing = []
    for path in EXAMPLE_PAGES:
        for example, stem in _markers(path):
            block = hooks.spine(f"examples.{example}.configs.{stem}")
            for row in block.splitlines():
                link = re.search(r"\]\(\.\./steps/([\w-]+)\.md\)", row)
                if not link:
                    continue
                page = (ROOT / "docs" / "steps" / f"{link.group(1)}.md").read_text()
                named = re.findall(r"`(\w+)`(?: =|:| is)", row)
                named += re.findall(r"overrides `(\w+)\(\)`", row)
                for field in named:
                    # `score_name` is inside `tester_score_name`.
                    if not re.search(rf"\b{re.escape(field)}\b", page):
                        missing.append(f"{example}/{stem}: `{field}` -> steps/{link.group(1)}.md")
    assert not missing, "spine rows naming a field their step page does not:\n  " + "\n  ".join(
        sorted(set(missing))
    )


@pytest.mark.parametrize("path", EXAMPLE_PAGES, ids=_doc_id)
def test_no_example_page_shows_code_for_a_step_it_does_not_change(path):
    """Re-showing an unchanged step makes a page read as a fresh start, not a continuation."""
    if path.name in SPINE_EXEMPT:
        return
    hooks = _hooks()
    changed = set()
    for example, stem in _markers(path):
        block = hooks.spine(f"examples.{example}.configs.{stem}")
        changed.update(re.findall(r"\]\(\.\./steps/([\w-]+)\.md\)", block))
    # Which step a --8<-- illustrates, from its directory. trainer/ is absent: every task
    # writes its own prep_batch.
    step_of_dir = {
        "dataloaders": "dataset",
        "models": "model",
        "losses": "loss",
        "metrics": "metrics",
        "optimizer": "optimizer",
        "augmentation": "dataset",
    }
    offenders = []
    for include in re.findall(r'--8<--\s+"(examples/[^"]+)"', path.read_text()):
        parts = Path(include).parts
        step = next((step_of_dir[p] for p in parts if p in step_of_dir), None)
        if step and step not in changed:
            offenders.append(f"{include} illustrates '{step}', which this example does not change")
    assert not offenders, f"{_doc_id(path)} shows code for an unchanged step:\n  " + "\n  ".join(
        offenders
    )


def test_the_config_page_example_is_the_scaffold_that_ci_trains():
    """The template cannot drift: the wheel job trains a project built from it on every commit."""
    from importlib.resources import files

    page = _render_generated_pages()["reference/config.md"]
    blocks = re.findall(r"```python[^\n]*\n(.*?)```", page, re.DOTALL)
    assert blocks, "the config page renders no example"

    source = files("gatle_ignite").joinpath("_template", "configs", "{{project_name}}_v0.py-tpl")
    template = source.read_text(encoding="utf-8").replace("{{project_name}}", "my_project")

    rendered = blocks[0].strip()
    assert rendered in template, "the config page example is not the scaffold verbatim"
    for field in ("criterion_name", "criterion_params", "optimizer_name", "main_runner"):
        assert f"cfg.{field}" in rendered, f"the worked config never sets {field}"
