"""Generate the reference pages from the code, at build time.

Nothing here is hand-maintained. The config fields, their defaults, types, section
headings and notes are read out of `gatle_ignite.config`; the entrypoint contracts come
from `dispatch.CONTRACTS`; the builtins are discovered by asking each module whether it
satisfies its contract; the CLI page is argparse's own help.

The point is that a field added to `base_config()` appears on the site with no docs edit,
and a renamed one cannot leave a stale name behind, because there is no second copy.
"""

import ast
import importlib
import inspect
import io
import pkgutil
import tokenize
from importlib.resources import files

import mkdocs_gen_files

from gatle_ignite.callbacks import logging as gi_logging
from gatle_ignite.cli.main import build_parser
from gatle_ignite.config import base
from gatle_ignite.dispatch import CONTRACTS

BANNER = "<!-- Generated by docs/gen_reference.py. Do not edit: edit the code it reads. -->"


# --------------------------------------------------------------------------------------
# config reference
# --------------------------------------------------------------------------------------


def _trailing_comments(src):
    """{line number: text} for every comment that FOLLOWS code on its own line.

    Found by token rather than by slicing a line, because a field's note is not reliably on
    the statement's LAST line. `ruff format` wraps a too-long `cfg.x = 1  # note` by
    parenthesising the value:

        cfg.max_epochs = (
            1  # note
        )

    which leaves `end_lineno` pointing at the `)` and the note a line above it. Slicing
    that last line then finds no `#`, and the field silently loses its Notes cell: a doc
    that goes blank with a green build, which is the exact failure this generator exists to
    prevent. Keyed by line so the caller can take whatever falls inside a statement's span,
    wherever the formatter put it.
    """
    comments = {}
    for tok in tokenize.generate_tokens(io.StringIO(src).readline):
        if tok.type != tokenize.COMMENT:
            continue
        if tok.line[: tok.start[1]].strip():  # code precedes it: trailing, not whole-line
            comments[tok.start[0]] = tok.string.lstrip("#").strip()
    return comments


def _walk_base_config():
    """Yield (section, name, default_src, note) for every `cfg.X = ...` in base_config().

    Read by AST rather than by introspecting the returned ConfigDict, because only the
    source carries the `# --- section ---` groupings and the per-field comments.
    """
    source = inspect.getsource(base)
    lines = inspect.getsourcelines(base)[0]
    tree = ast.parse(source)
    trailing = _trailing_comments(source)
    fn = next(n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name == "base_config")

    section = None
    for stmt in fn.body:
        if not (isinstance(stmt, ast.Assign) and isinstance(stmt.targets[0], ast.Attribute)):
            continue

        notes = []
        i = stmt.lineno - 2  # whole-line comments directly above the assignment
        while i >= 0 and lines[i].strip().startswith("#"):
            text = lines[i].strip().lstrip("#").strip()
            if text.startswith("---") and text.endswith("---"):
                section = text.strip("- ")
            else:
                notes.insert(0, text)
            i -= 1

        # Anywhere in the statement's span, not only its last line -- see _trailing_comments.
        notes.extend(
            text
            for line, text in sorted(trailing.items())
            if stmt.lineno <= line <= stmt.end_lineno
        )

        yield section, stmt.targets[0].attr, ast.unparse(stmt.value), " ".join(notes)


def _cell(text):
    """Escape a value for a markdown table cell.

    An unescaped pipe silently truncates the row, and the field most likely to contain
    one is `amp_dtype`, whose entire documentation is the comment `auto | bf16 | fp16 |
    fp32`. Without this it renders as just "auto", and no build warning says so.
    """
    return text.replace("|", "\\|")


def _render_default(src):
    return "_unset_" if "placeholder(" in src else f"`{_cell(src)}`"


def _template_config():
    """`init`'s own config, as the site's worked example. -> str

    Read from the scaffold rather than retyped, for the reason where_things_go_page reads
    it: a second copy of a config is a copy that stops training and says nothing. The
    wheel job builds a project from this template and trains it every commit.
    """
    source = files("gatle_ignite").joinpath("_template", "configs", "{{project_name}}_v0.py-tpl")
    body = source.read_text(encoding="utf-8").replace("{{project_name}}", "my_project")
    tree = ast.parse(body)
    doc = ast.get_docstring(tree, clean=False)
    if doc is not None:
        # The module docstring says what this page's own prose just said. Dropped by line
        # number rather than by string, so a reworded scaffold still renders.
        body = "\n".join(body.split("\n")[tree.body[0].end_lineno :])
    return body.strip()


def config_page():
    cfg = base.base_config()
    out = io.StringIO()
    print("# Config fields\n", file=out)
    print(BANNER, file=out)
    print(
        "\nStart from `base_config()`: every optional field already has a value, so a config"
        " only states what it changes.\n",
        file=out,
    )

    print("\n## A config, whole\n", file=out)
    print(
        "What `gatle-ignite init` writes, minus its file docstring. It trains as it stands,"
        ' so it is also the shortest correct answer to "what must a config say?". The tables'
        " below are the menu of what else it *could* say.\n",
        file=out,
    )
    print('```python title="configs/my_project_v0.py"', file=out)
    print(_template_config(), file=out)
    print("```\n", file=out)

    current = None
    for section, name, default_src, note in _walk_base_config():
        if section != current:
            current = section
            print(f"\n## {section}\n", file=out)
            print("| Field | Type | Default | Notes |", file=out)
            print("|---|---|---|---|", file=out)
        try:
            type_name = cfg.get_type(name).__name__
        except Exception:
            type_name = type(cfg.get(name)).__name__
        required = " **(required)**" if name in base.REQUIRED_FIELDS else ""
        print(
            f"| `{name}`{required} | `{type_name}` | {_render_default(default_src)} | {_cell(note)} |",
            file=out,
        )

    print("\n## Fields not pre-set by `base_config()`\n", file=out)
    print(
        "These are known to the framework but deliberately absent from `base_config()`,"
        " because their *presence* is what carries the meaning. A ConfigDict accepts new"
        " keys, so a config sets them directly.\n",
        file=out,
    )
    print("| Field | Meaning |", file=out)
    print("|---|---|", file=out)
    for name, note in base.OPTIONAL_KNOWN.items():
        print(f"| `{name}` | {_cell(note)} |", file=out)

    print(
        "\n## Your own fields\n\n"
        "Any other field is left alone, so a config can carry values that only your own"
        " trainer or dataset reads.\n",
        file=out,
    )
    return out.getvalue()


# --------------------------------------------------------------------------------------
# entrypoint contracts
# --------------------------------------------------------------------------------------


def contracts_page():
    out = io.StringIO()
    print("# Entrypoint contracts\n", file=out)
    print(BANNER, file=out)
    print(
        "\nEvery component is selected by a dotted module path in the config, imported at"
        " runtime. There is no registry and no decorator: to add a component, write a module"
        " that exposes the expected name and point a config field at it.\n",
        file=out,
    )
    print("| Config field | Must expose | Contract |", file=out)
    print("|---|---|---|", file=out)
    for field, attr, contract, _fields in CONTRACTS:
        print(f"| `{_cell(field)}` | `{attr}` | {_cell(contract)} |", file=out)
    print(
        '\n!!! note "One exception"\n'
        "    `cfg.logger_name` is a list of enabled sinks and *does* accept short names"
        " for the builtins. See [Logging](../steps/logging.md).\n",
        file=out,
    )
    print(
        "\nA path that does not import, or a module missing its entrypoint, raises"
        " `ConfigError` naming the config field at fault and listing what the module"
        " actually exports.\n",
        file=out,
    )
    return out.getvalue()


# --------------------------------------------------------------------------------------
# builtins
# --------------------------------------------------------------------------------------

# (package, the entrypoint a module must expose to count, modules to skip)
BUILTIN_PACKAGES = (
    ("gatle_ignite.optimizers", "get_optimizer", ()),
    ("gatle_ignite.schedulers", "get_scheduler", ()),
    ("gatle_ignite.callbacks.backends", "Backend", ()),
)


def _params_of(entrypoint):
    """The configurable params of a builtin, read from its signature.

    Skips the positional plumbing the framework passes in (model, cfg, engine_type, ...)
    and reports what a config actually sets, with defaults.
    """
    import inspect

    framework_supplied = {
        "self",
        "model",
        "cfg",
        "train_dl",
        "optimizer",
        "trainer",
        "evaluator",
        "engine_type",
        "info",
        "dataset",
    }
    try:
        sig = inspect.signature(entrypoint)
    except (TypeError, ValueError):
        return ""

    parts = []
    for name, p in sig.parameters.items():
        if name in framework_supplied or p.kind is p.VAR_POSITIONAL:
            continue
        if p.kind is p.VAR_KEYWORD:
            parts.append("**kwargs")
            continue
        parts.append(name if p.default is p.empty else f"{name}={p.default!r}")
    return ", ".join(f"`{p}`" for p in parts)


def builtins_page():
    out = io.StringIO()
    print("# Builtins\n", file=out)
    print(BANNER, file=out)
    print(
        "\nBuiltins are ordinary modules with no special status. They are named by their"
        ' **full dotted path**. There is no alias table, so `"adamw"` does not resolve'
        ' and `"gatle_ignite.optimizers.adamw"` does. Swapping a builtin for your own is'
        " changing this string.\n",
        file=out,
    )
    print(
        '!!! note "One exception"\n'
        "    `cfg.logger_name` *does* accept short names: see the table at the bottom of"
        " this page, and [Logging](../steps/logging.md).\n",
        file=out,
    )

    for pkg_name, attr, exclude in BUILTIN_PACKAGES:
        pkg = importlib.import_module(pkg_name)
        print(f"\n## `{pkg_name}`\n", file=out)
        print(f"Each module exposes `{attr}`.\n", file=out)
        print("| Dotted path | What it is | Params |", file=out)
        print("|---|---|---|", file=out)
        for info in pkgutil.walk_packages(pkg.__path__, pkg_name + "."):
            leaf = info.name.rsplit(".", 1)[-1]
            if leaf.startswith("_") or leaf in exclude:
                continue
            mod = importlib.import_module(info.name)
            if not hasattr(mod, attr):
                continue
            blurb = (mod.__doc__ or "").strip().split("\n")[0]
            params = _params_of(getattr(mod, attr))
            print(f"| `{info.name}` | {_cell(blurb)} | {_cell(params)} |", file=out)

    print("\n## `cfg.logger_name`\n", file=out)
    print(
        "The one field that takes short names. It is a list of *enabled sinks*, not a"
        " component path, which is why it reads differently from everything above.\n",
        file=out,
    )
    print("| Name | Resolves to |", file=out)
    print("|---|---|", file=out)
    for name in gi_logging.BUILTIN_BACKENDS:
        print(f'| `"{name}"` | `gatle_ignite.callbacks.backends.{name}` |', file=out)
    for name in gi_logging.NOT_A_BACKEND:
        print(f'| `"{name}"` | **not a backend**: a flag handled by the trainer |', file=out)
    print(
        "\nAny name containing a dot is treated as a dotted path to your own module"
        " exposing `Backend(cfg)`.\n",
        file=out,
    )
    return out.getvalue()


# --------------------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------------------


def cli_page():
    out = io.StringIO()
    print("# The CLI\n", file=out)
    print(BANNER, file=out)
    print(
        "\n`python -m gatle_ignite <cmd>` is equivalent to `gatle-ignite <cmd>`. Use that"
        " form under SLURM.\n",
        file=out,
    )
    parser = build_parser()
    print("```text", file=out)
    print(parser.format_help().rstrip(), file=out)
    print("```", file=out)

    subparsers = parser._subparsers._group_actions[0].choices
    for name, sub in subparsers.items():
        print(f"\n## `gatle-ignite {name}`\n", file=out)
        print("```text", file=out)
        print(sub.format_help().rstrip(), file=out)
        print("```", file=out)
    return out.getvalue()


# --------------------------------------------------------------------------------------


def where_things_go_page():
    """The scaffold README's layout table, so the site and `init` cannot drift apart."""
    source = files("gatle_ignite").joinpath("_template", "README.md-tpl")
    template = source.read_text(encoding="utf-8").replace("{{project_name}}", "my_project")
    start = template.index("## Where things go")
    end = template.index("Copy-paste templates", start)

    out = io.StringIO()
    print("# Where things go\n", file=out)
    print(BANNER, file=out)
    print(
        "\nThe table `gatle-ignite init` writes into your project's README, generated from that"
        " same file so the two cannot drift.\n",
        file=out,
    )
    print(template[start:end].split("\n", 1)[1].strip(), file=out)
    print("\nCopy-paste skeletons for each: [Templates](../templates.md).", file=out)
    return out.getvalue()


PAGES = (
    (
        "reference/where-things-go.md",
        where_things_go_page,
        "src/gatle_ignite/_template/README.md-tpl",
    ),
    ("reference/config.md", config_page, "src/gatle_ignite/config/base.py"),
    ("reference/contracts.md", contracts_page, "src/gatle_ignite/dispatch.py"),
    ("reference/builtins.md", builtins_page, "docs/gen_reference.py"),
    ("getting-started/cli.md", cli_page, "src/gatle_ignite/cli/main.py"),
)

for path, render, edit_hint in PAGES:
    with mkdocs_gen_files.open(path, "w") as f:
        f.write(render())
    # Point Material's edit pencil at the source, not at a file that doesn't exist,
    # so the next reader learns where the truth lives.
    mkdocs_gen_files.set_edit_path(path, edit_hint)
